name: simple_rate_my_app
description: Simple way to get user rating
version: 3.0.2
homepage: https://github.com/thize/simple_rate_my_app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  in_app_review: ^2.0.1
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter: